### ISSUE TITLE
Invalid or unsupported zip format. No END header found

### ISSUE THREAD

**Issue by neocafe** [Gravit-io/gravit-designer-plugin-starter#6]
Using: Windows 10
NodeJS : 8.9.1 LTS

After running node install I'm getting this error msg:

node build.js
Downloading Gravit Designer...
c:\WORK\gravit\node_modules\adm-zip\zipFile.js:66
            throw Utils.Errors.INVALID_FORMAT;
"Invalid or unsupported zip format. No END header found"
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gravit-designer-plugin-starter@1.0.0 install: `node build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gravit-designer-plugin-starter@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by dennererthal01** [comment]
The following PR should fix the issue: https://github.com/Gravit-io/gravit-designer-plugin-starter/pull/7
